[package]
name = "robotics_program"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
rfd = "0.10.0"
pyo3 = "0.17.2"
calamine = "0.19.1"


# [features]
# my_debug = []
